
import 'package:task_c/model/medical_article_model.dart';

class MedicalArticleController{


  Future<List<MedicalArticleModel>> searchMedicalArticle({String? name})async {
    List<MedicalArticleModel> medicalArticleModel = [];
    for(int i =0; i<listMedicalArticleModels.length; i++){
      if(listMedicalArticleModels[i].name!.contains(name!)){
        medicalArticleModel.add(listMedicalArticleModels[i]);
      }
    }
    return medicalArticleModel;
  }

  Future<List<MedicalArticleModel>> getMedicalArticle()async {
    listMedicalArticleModels = [
      MedicalArticleModel(name: "Abdominal aortic aneurysms",description: 'An abdominal aortic aneurysm (AAA) is a swelling (aneurysm) of the aorta – the main blood vessel that leads away from the heart, down through the abdomen to the rest of the body. The abdominal aorta is the largest blood vessel in the body and is usually around 2cm wide – roughly the width of a garden hose. However, it can swell to over 5.5cm – what doctors class as a large AAA. Large aneurysms are rare, but can be very serious. If a large aneurysm bursts, it causes huge internal bleeding and is usually fatal. The bulging occurs when the wall of the aorta weakens. Although what causes this weakness is unclear, smoking and high blood pressure are thought to increase the risk of an aneurysm.',date: "19th May 2022"),
      MedicalArticleModel(name: "Acne",description: 'An abdominal aortic aneurysm (AAA) is a swelling (aneurysm) of the aorta – the main blood vessel that leads away from the heart, down through the abdomen to the rest of the body. The abdominal aorta is the largest blood vessel in the body and is usually around 2cm wide – roughly the width of a garden hose. However, it can swell to over 5.5cm – what doctors class as a large AAA. Large aneurysms are rare, but can be very serious. If a large aneurysm bursts, it causes huge internal bleeding and is usually fatal. The bulging occurs when the wall of the aorta weakens. Although what causes this weakness is unclear, smoking and high blood pressure are thought to increase the risk of an aneurysm.',date: "19th May 2022"),
      MedicalArticleModel(name: "Cholecystitis",description: 'An abdominal aortic aneurysm (AAA) is a swelling (aneurysm) of the aorta – the main blood vessel that leads away from the heart, down through the abdomen to the rest of the body. The abdominal aorta is the largest blood vessel in the body and is usually around 2cm wide – roughly the width of a garden hose. However, it can swell to over 5.5cm – what doctors class as a large AAA. Large aneurysms are rare, but can be very serious. If a large aneurysm bursts, it causes huge internal bleeding and is usually fatal. The bulging occurs when the wall of the aorta weakens. Although what causes this weakness is unclear, smoking and high blood pressure are thought to increase the risk of an aneurysm.',date: "19th May 2022"),
      MedicalArticleModel(name: "Lymphoblastic leukaemia",description: 'An abdominal aortic aneurysm (AAA) is a swelling (aneurysm) of the aorta – the main blood vessel that leads away from the heart, down through the abdomen to the rest of the body. The abdominal aorta is the largest blood vessel in the body and is usually around 2cm wide – roughly the width of a garden hose. However, it can swell to over 5.5cm – what doctors class as a large AAA. Large aneurysms are rare, but can be very serious. If a large aneurysm bursts, it causes huge internal bleeding and is usually fatal. The bulging occurs when the wall of the aorta weakens. Although what causes this weakness is unclear, smoking and high blood pressure are thought to increase the risk of an aneurysm.',date: "19th May 2022"),
      MedicalArticleModel(name: "Pancreatitis",description: 'An abdominal aortic aneurysm (AAA) is a swelling (aneurysm) of the aorta – the main blood vessel that leads away from the heart, down through the abdomen to the rest of the body. The abdominal aorta is the largest blood vessel in the body and is usually around 2cm wide – roughly the width of a garden hose. However, it can swell to over 5.5cm – what doctors class as a large AAA. Large aneurysms are rare, but can be very serious. If a large aneurysm bursts, it causes huge internal bleeding and is usually fatal. The bulging occurs when the wall of the aorta weakens. Although what causes this weakness is unclear, smoking and high blood pressure are thought to increase the risk of an aneurysm.',date: "19th May 2022"),
      MedicalArticleModel(name: "Bacterial vaginosis",description: 'An abdominal aortic aneurysm (AAA) is a swelling (aneurysm) of the aorta – the main blood vessel that leads away from the heart, down through the abdomen to the rest of the body. The abdominal aorta is the largest blood vessel in the body and is usually around 2cm wide – roughly the width of a garden hose. However, it can swell to over 5.5cm – what doctors class as a large AAA. Large aneurysms are rare, but can be very serious. If a large aneurysm bursts, it causes huge internal bleeding and is usually fatal. The bulging occurs when the wall of the aorta weakens. Although what causes this weakness is unclear, smoking and high blood pressure are thought to increase the risk of an aneurysm.',date: "19th May 2022"),
      MedicalArticleModel(name: "Benign prostate enlargement",description: 'An abdominal aortic aneurysm (AAA) is a swelling (aneurysm) of the aorta – the main blood vessel that leads away from the heart, down through the abdomen to the rest of the body. The abdominal aorta is the largest blood vessel in the body and is usually around 2cm wide – roughly the width of a garden hose. However, it can swell to over 5.5cm – what doctors class as a large AAA. Large aneurysms are rare, but can be very serious. If a large aneurysm bursts, it causes huge internal bleeding and is usually fatal. The bulging occurs when the wall of the aorta weakens. Although what causes this weakness is unclear, smoking and high blood pressure are thought to increase the risk of an aneurysm.',date: "19th May 2022"),
      MedicalArticleModel(name: "Bile duct cancer",description: 'An abdominal aortic aneurysm (AAA) is a swelling (aneurysm) of the aorta – the main blood vessel that leads away from the heart, down through the abdomen to the rest of the body. The abdominal aorta is the largest blood vessel in the body and is usually around 2cm wide – roughly the width of a garden hose. However, it can swell to over 5.5cm – what doctors class as a large AAA. Large aneurysms are rare, but can be very serious. If a large aneurysm bursts, it causes huge internal bleeding and is usually fatal. The bulging occurs when the wall of the aorta weakens. Although what causes this weakness is unclear, smoking and high blood pressure are thought to increase the risk of an aneurysm.',date: "19th May 2022"),
      MedicalArticleModel(name: "Binge eating disorder",description: 'An abdominal aortic aneurysm (AAA) is a swelling (aneurysm) of the aorta – the main blood vessel that leads away from the heart, down through the abdomen to the rest of the body. The abdominal aorta is the largest blood vessel in the body and is usually around 2cm wide – roughly the width of a garden hose. However, it can swell to over 5.5cm – what doctors class as a large AAA. Large aneurysms are rare, but can be very serious. If a large aneurysm bursts, it causes huge internal bleeding and is usually fatal. The bulging occurs when the wall of the aorta weakens. Although what causes this weakness is unclear, smoking and high blood pressure are thought to increase the risk of an aneurysm.',date: "19th May 2022"),
      MedicalArticleModel(name: "Bipolar disorder",description: 'An abdominal aortic aneurysm (AAA) is a swelling (aneurysm) of the aorta – the main blood vessel that leads away from the heart, down through the abdomen to the rest of the body. The abdominal aorta is the largest blood vessel in the body and is usually around 2cm wide – roughly the width of a garden hose. However, it can swell to over 5.5cm – what doctors class as a large AAA. Large aneurysms are rare, but can be very serious. If a large aneurysm bursts, it causes huge internal bleeding and is usually fatal. The bulging occurs when the wall of the aorta weakens. Although what causes this weakness is unclear, smoking and high blood pressure are thought to increase the risk of an aneurysm.',date: "19th May 2022"),

    ];
    return listMedicalArticleModels;
  }

}